soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
=> add soql function magnitude

soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala, soql-types/src/test/scala-2.10/com/socrata/soql/types/SoQLGeometryLikeTest.scala
- Add a WKB64 (base64 WKB) translator
- Use thread local encoders/decoders for speed improvement
- Add a SoQLBinaryGeometry for pass-through / more efficient encoding
=> Geometry SoQL improvements

project/SoqlTypes.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeConversions.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala, soql-types/src/test/scala-2.10/com/socrata/soql/types/SoQLGeometryLikeTest.scala
* Added polygon, line, and multipoint types
* added tests for wkt adn wkb serialization
* todo: remove the snapshot reference in dependencies
=> Refs CORE-5412

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/LexerReader.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala
Just the one in the select level.
SELECT DISTINCT col1, col2, …
not the one inside function
SELECT COUNT(DISTINCT col1)
=> EN-14996 Add “Distinct” support

soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
These functions provide support for the apps team.
=> EN-14870 Add date_part_xxx(floating_timestamp) functions.

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
enough for soqls generated for default views in core server to work.
=> EN-16339 Make chaining/merging work with joins to some degree

soql-analyzer/src/main/scala/com/socrata/soql/typed/Join.scala
I'll need to bump version everything after this.
=> EN-16372 Missing something for full outer join support.

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, soql-analyzer/src/main/scala/com/socrata/soql/typed/Join.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Join.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala, soql-types/src/test/scala/com/socrata/soql/types/SoQLGeometryLikeTest.scala
Partial sub-queries support to allow processing joins with derived views.
=> Chi/en 16370/sub queries

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
EN-16601 Add more date extract functions
=> EN-16601 Floating timestamp date part extract functions - date_extract_label style

soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala, soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ToStringTest.scala
=> Make SoQLNode -> String functions format the output

soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala, soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ParserTest.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
1. Support order by
2. Add row_number, rank, dense_rank
=> EN-31669 Window function support, phase 2

soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
Window function expressions are always of the form `function(args)
over (more args)` but the grammar would accept `identifier over (more
args)`
Also, the `windowFunctionParams` term could never produce a Left, so
de-either it.  This gets rid of a partial function call in the
function call term.
Also silence a warning.
=> Fix window function parsing

soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
This is significantly more complicated, but much MUCH faster for deeply
nested expressions
=> Change Expression.toString to no longer be superlinear

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala, version.sbt
Should be able to handle boolean_field = ‘TRUE’
=> EN-33655 Add text to boolean auto cast

project/build.sbt
https://github.com/lightbend/mima/issues/422
addressing the above issue which is breaking builds.
=> add specific resolver given mima was moved

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeClasses.scala
Specify SoQL functions:
Datediff in seconds
Absolute
=> EN-37621, EN-37687 date-x - date-y -> z seconds, abs(x) => y

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala, version.sbt
=> EN-40991: Fix missing replaceRefs in window function info

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, version.sbt
Add SoQL function to extract the isoyear from a floating timestamp.
=> EN-41224: Add extract isoyear

soql-analyzer/src/test/scala/com/socrata/soql/parsing/ParserTest.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/LexerReader.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala
* Using the postgresql reserved-words list as a guideline:
https://www.postgresql.org/docs/12/sql-keywords-appendix.html
* As a side effect, "NULLS FIRST" / "NULLS LAST" is now accepted.
* so is "NULL FIRST" / "NULL LAST" because backwards compat
=> Un-reserve certain reserved words

soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala, soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ParserTest.scala, version.sbt
Count distinct still does not work with window function.  It is not supported in Postgres (at least in v11) anyway.
=> EN-42634: count expression/* + window function

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeClasses.scala, version.sbt
* so we can turn something into jsonb
* subscripts work with commit in pg-adapter
=> EN-45612 Add text to json cast

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, version.sbt
Added functions and docs for:
`regr_slope`
`regr_intercept`
`regr_r2`
`ln`
=> regression analysis functions and natural log function

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, soql-analyzer/src/main/scala/com/socrata/soql/exceptions/Exceptions.scala, soql-analyzer/src/main/scala/com/socrata/soql/functions/Function.scala, soql-analyzer/src/main/scala/com/socrata/soql/functions/MonomorphicFunction.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/FunctionInfo.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctionInfo.scala, soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctionInfo.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
Advice about how to scala better is also welcome.
=> add needsWindow to window functions

soql-analyzer/src/main/scala/com/socrata/soql/typechecker/FunctionInfo.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala, soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala, soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctionInfo.scala, soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctionInfo.scala, version.sbt
Aggregate functions can have window info
=> EN-46931: Fix window function check

soql-analyzer/src/main/scala/com/socrata/soql/exceptions/Exceptions.scala
Also did some re-ordering and re-labelling to help make it obviouser that, yes. You should always codec your SoQLExceptions.
=> EN-47330: Add codecs for new exceptions.

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, version.sbt
- Crosses: alias of ST_CROSSES in Postgis https://postgis.net/docs/ST_Crosses.html
- Overlaps: alias of ST_OVERLAPS in Postgis https://postgis.net/docs/ST_Overlaps.html
=> add Crosses and Overlaps; bump version;

soql-analyzer/src/test/scala/com/socrata/soql/types/TestType.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala, version.sbt
=> Add interval datatype

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/HintTypechecker.scala, soql-analyzer/src/main/scala/com/socrata/soql/typed/Hint.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Hint.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentHintParser.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentParser.scala, soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ToStringTest.scala
=> EN-49524: Add unique order hint

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/HintTypechecker.scala, soql-analyzer/src/main/scala/com/socrata/soql/typed/Hint.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Hint.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentHintParser.scala, soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentParser.scala, soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ToStringTest.scala, version.sbt
Add: NO_ROLLUP, NO_CHAIN_MERGE
Delete: UNIQUE_INDEX
=> EN-50442: Add/delete hints

soql-stdlib/src/main/scala/com/socrata/soql/stdlib/Context.scala
The common case will be to NOT have all the various bits filled out, so
make the JSON serialization omit them if they're empty
=> Make contexts smaller on the wire

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala, version.sbt
Check for no join alias collision
No having on the left
=> EN-54074: Allow chained soql merge when both left and right have joins

soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
I have no idea why this clause was here?
=> Remove apparently unnecessary special case in the Typechecker

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/From.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Statement.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/TableMap.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromSingleRow.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromStatement.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromTable.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/Join.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/CTE.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/CombinedTables.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Values.scala
* In a TableMap, or
* In an analysis
=> Add utilities for finding all referenced physical tables

version.sbt
Bumping version to do a release build.
There is a column name mapping fix that needs to be propagated.
=> bumping version

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeClasses.scala
..in aggregate and non-aggregate form, in preparation for de-aggregating `concave_hull` and `convex_hull`
=> Add `spatial_union` function

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzerError.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala, soql-analyzer/src/main/scala/com/socrata/soql/typechecker/TypeInfo.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestTypeInfo.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala, soql-types/src/main/scala/com/socrata/soql/types/obfuscation/CryptProvider.scala
* Add provenance to soqlid and soqlversion, and teach analyzer2 to populate it
* Fix analyzer2 typechecking window functions' order bys
=> analyzer2 enhancements

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Pass.scala
Since each one represents a single pass
=> Rename rewrite.Passes to rewrite.Pass

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, version.sbt
=> width_bucket soql function

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
Each such comment is commented with a reason for it to be in this state.
=> EN-60584: Mark various functions deprecated or hidden

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/PreserveOrdering.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala
In the case where a query-chain orders one way and then orders by the same column another way.
=> Make the preserve ordering rewrite produce less redundant clauses

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/FoundTables.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/FoundTablesTableFinder.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/UnparsedFoundTables.scala
* Add a "version" field to FoundTables' serialization
* Make it so that a FoundTables can be edited
=> FoundTables utilities

build.sbt, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzerError.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Stringifier.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/AggregateFunctionCall.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/FunctionSplitter.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/FunctionSubset.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupExact.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupInfo.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupRewriter.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/SplitAnd.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/SsemigroupRewriter.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/package.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestFunctions.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupExactTest.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupRewriterTest.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupTestHelper.scala, soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLFunctionSplitter.scala, soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLFunctionSubset.scala, soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLRollupExact.scala, soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLSemigroupRewriter.scala, soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLSplitAnd.scala, soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLSemigroupRewriterTest.scala, soql-toy/src/main/scala/com/socrata/soql/Main.scala, soql-toy/src/main/scala/com/socrata/soql/Soql2Toy.scala, soql-utils/src/main/scala/com/socrata/soql/util/LazyToString.scala
=> Move rollups into soql reference

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzerError.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/AggregateFunctionCall.scala, soql-toy/src/main/scala/com/socrata/soql/Main.scala, soql-toy/src/main/scala/com/socrata/soql/Soql2Toy.scala
Use with `sbt 'soqlToy/run soql2'`
=> Implement soqltoy via analyzer2

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Rep.scala
And define the latter in terms of the former.
These are the same for most types, but provenanced columns grow an additional virtual one.
=> Separate "physical" and "expanded" schemas in columns' Reps

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/From.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/PhysicalColumn.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala
To mimic old-analyzer, which allows it.
=> More flexible this in the new-analyzer

CODEOWNERS
Add a CODEOWNERS file so that we can get automatic PR assignment.
=> NOJIRA: Initial check-in of codeowners file for PR assignment

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Rep.scala
rather than writing csv itself
=> Make the Rep's csvify method produce a seq of cells

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/LimitIfUnlimited.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Pass.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala
* A rewrite pass for adding a default limit if necessary
* Reworking SoQLGeometry to do less allocation
=> Default limits and geometries

build.sbt, soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/ExprSqlizer.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/SqlizerTest.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestFunctionInfo.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestFunctionSqlizer.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestFunctions.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestHelper.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestRepProvider.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestRewriteSearch.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestType.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestTypeInfo.scala
..also bring the whole sqlizer test suite over from soql-postgres where the sqlizer code originated.
=> Fix `order by compressed_provenanced_value`

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/ExprSqlizer.scala, soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/SelectListIndex.scala, soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Sqlizer.scala, soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/SqlizerUniverse.scala, soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestHelper.scala
To make what we want to do with it even easier
=> Rework the order-by extension type a little.

soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala, soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala, soql-types/src/main/scala/com/socrata/soql/types/cjson.scala
So that there's one central place for what that means.
=> Bring cjson encoders/decoders over from data-coordinator

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupExact.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupExactTest.scala
See the new test in RollupExactTest for details
=> Fix an edge-case involving rollups and count(*)

soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/PreserveSystemColumnsAggregateMerger.scala
Because dsmapi will need it too.
=> Bring the system columns' aggregate merger from QC into soql-stdlib

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala, soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeClasses.scala
This reverts commit 4ba85884e08ff2c1680510c340eb5bbbdc49756a.
=> Revert "EN-66000: Don't accept id or version values in concat"

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/TableMap.scala
It's possible (albeit uncommon) for a table to have more than one referencing ScopedResourceName so this produces a map from DTN to a non-empty seq of scoped resource names.
=> Helper for looking up found tables by their database table name

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/PreserveUnique.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala
Before it would try to pull up unique columns from such a query's FROM, which can't happen - if a query is aggregated, then its source of uniqueness is its GROUP BY clause.
=> Fix impose ordering rewrite pass on nested group bys

soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupExactTest.scala
I didn't actually think it _did_ do this, because of its implicitness, but it totally makes sense when reading the code.  Adding the test to make sure it continues to make sense when reading the code.
=> Add a test for a useful but implicit thing RollupExact does

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala
Missed this bit in the previous PR
=> Add `removeSystemColumns` to SoQLAnalysis

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/TableFinder.scala, soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TableFinderTest.scala
Before, if you were tablefinding from query A that called B that called A, the table finder would report the error at B.  Now it runs up the stack to find the start of the loop and reports the error there.  This is better because "interior" errors might not get shown to the end-user (as they may not have access to interior saved queries), so this maximizes the possibility for the error to be actionable.
=> Report recursive-query errors at the highest level possible

soql-toy/src/main/scala/com/socrata/soql/AnalyzeFoundTables.scala, soql-toy/src/main/scala/com/socrata/soql/Main.scala
This isn't really much of a "toy" in the sense of "sample program for exploration" that's used elsewhere, but I don't really have a better place to put it.
=> Add AnalyzeFoundTables toy

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
It had expected-params/got-params backward
=> Fix UDF parameter count error

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/NamedExpr.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/PositionInfo.scala, soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromTable.scala, soql-serialize/src/main/scala/com/socrata/soql/serialize/Buffer.scala, soql-utils/src/main/scala/com/socrata/soql/sql/Debug.scala
Also get rid of serialization versions 0, 1, and 2 as they are all well obsolete at this point.
=> EN-77403: Add `mergeSystemColumns` flag

version.sbt
=> update version sbt
