README.md
project/Build.scala
project/SoqlPack.scala
project/build.sbt
soql-pack/src/main/scala/com.socrata.soql/SoQLPackDecoder.scala
soql-pack/src/main/scala/com.socrata.soql/SoQLPackDumper.scala
soql-pack/src/main/scala/com.socrata.soql/SoQLPackEncoder.scala
soql-pack/src/main/scala/com.socrata.soql/SoQLPackIterator.scala
soql-pack/src/main/scala/com.socrata.soql/SoQLPackWriter.scala
soql-pack/src/test/scala/com.socrata.soql/SoQLPackTest.scala
soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala

Overall, this PR moves SoQLPack logic from soda-fountain and tileserver to a centralized place here in soql-reference and extends support to far more types.
- Generic API to encode an `Iterator[Array[SoQLValue]]` to a binary SoQLPack stream, and back
- SoQLPackDumper utility to dump out a binary SoQLPack stream on STDIN
- Support for every SoQL type except for the JSON types (SoQLArray, SoQLObject, etc).  These will be added later, in this PR or another one.
The plan after this is to 
a) replace code in soda-fountain and tileserver to use this API
b) enable tileserver to use SoQLPack for all queries
c) enable RegionCoder to pull from soda fountain using SoQLPack
It might be easier to review the individual commits.

SoQLPack library

---

soql-pack/src/main/scala/com.socrata.soql/SoQLPackDecoder.scala
soql-pack/src/main/scala/com.socrata.soql/SoQLPackEncoder.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeConversions.scala
soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala

Blobs are, as far as SoQL proper is concerned, an opaque identifier
which can be compared for equality with other blobs, but are not
ordered.
There'll need to be a version bump to actually use it, of course.

Blob values

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeClasses.scala

* Allows grouping on geometry columns, which was broken
in the previous release

Add geo types to Equatable

---

soql-analyzer/src/main/scala/com/socrata/soql/aliases/AliasAnalysis.scala
soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala

e.g., `select location(loc, this, that, theother) as loc`
Arbitrary circular references are still disallowed; only self-shadowing
is permitted.

Allow self-shadowing of columns

---

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/aliases/AliasAnalysis.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/SubscriptConverter.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/typed/CoreExpr.scala
soql-analyzer/src/main/scala/com/socrata/soql/typed/OrderBy.scala
soql-analyzer/src/main/scala/com/socrata/soql/typed/package.scala
soql-analyzer/src/test/scala/com/socrata/soql/AnalysisSerializationTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/parsing/ParserTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala
soql-environment/src/main/scala/com/socrata/soql/environment/TableName.scala
soql-standalone-parser/src/main/jflex/SoQLLexer.flex
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ParserTest.scala
soql-toy/src/main/scala/com/socrata/soql/AliasToy.scala
soql-toy/src/main/scala/com/socrata/soql/SoqlToy.scala
version.sbt

Basic join support
Qualified star selection
Use @aaaa-aaaa.field_name syntax
Join table alias
Automatically add prefix ‘_’ in the parse tree so that end user can address resource name with just the 4x4 and no prefixes despite that the real resource name is always prefixed with ‘_’.

SoQL Join (Qualifier is moved from ColumnName to ColumnRef)

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/parsing/Parser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/StandaloneParser.scala

DSMAPI doesn't need these and we can get a better error message if
trying to use them is a parse error.

Make joins optional at the parse level

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/aliases/AliasAnalysis.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala

There can be * from more than one table.  But :* is still limited to one table because system columns always contain name collisions.

EN-16454 Support multiple “SELECT *”’s

---

soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala

aggregate_fn(field) over (partition by x, y…)

“Partition by” should not be optional if the list is not empty.

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

Some `ST_MakeValid` calls return `GEOMETRYCOLLECTION` which we don't handle, so we need to call `ST_CollectionExtract` to turn it back into `MULTIPOLYGON`s

EN-19155: add geo collection extract functions

---

soql-analyzer/src/main/scala/com/socrata/soql/functions/Function.scala
soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctionInfo.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctionInfo.scala

This is for functions like `case`, which takes varargs in pairs
instead of one-by-one

Ensure that variadic application is correct when varargs length > 1

---

soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala

* On super large expressions, the foldright in the typechecker
would overflow the stack. This makes it fold right in constant
stack space

Fix stackoverflow

---

soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala

column_x as @table.x2 // invalid
column_x as x2 // valid

Qualification is not needed in column alias

---

soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala

So that we can do max(:id) as :id.  This help interoperability with obe

EN-23592 system column names in column aliases

---

project/SoqlParser.scala
version.sbt

restricting this to a specific version as artifactory appears to have  issues resolving when [ranges) are used. I'll see if I can find a bug on that later.

change the requested version to be explicit rather than use a range

---

soql-pack/src/main/scala/com.socrata.soql/SoQLPackWriter.scala

This facilitates adding missing rows_loaded metric support in NBE.

EN-36489 Return number of rows written

---

soql-standalone-parser/src/main/jflex/SoQLLexer.flex

If someone on Windows pastes soql into the soql editor, it can end up
with CRLF-style newlines.  We should tolerate that.

Support carriage returns as whitespace

---

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/aggregates/AggregateChecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/functions/MonomorphicFunction.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/FunctionCallTypechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/typed/CoreExpr.scala
soql-analyzer/src/test/scala/com/socrata/soql/AnalysisSerializationTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/parsing/ParserTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/types/TestTypeInfo.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/LexerReader.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ParserTest.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala

It was jamming window function parameter into the regular parameters.  This is changed to have its own properties in function ast.  Thought about splitting window functions and non window functions but I think that is unnecessary.
TODO: Add isWindowFunction to allow further validation

EN-40709: Support frame clause in window functions

---

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/test/scala/com/socrata/soql/AnalysisSerializationTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
version.sbt

. Use the new style in analysis serializer
. Remove old serialization stuff
. Refine window function syntax

EN-40991: Window function refactor part II (part I EN-40709)

---

soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/test/scala/com/socrata/soql/parsing/ParserTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala

With this change, both the legacy functional form
```
case(if1, then1, if2, then2, ...)
````
and
````
case
when if1 then then1
when if2 then then2
...
[else otherwise]
end
````
are accepted.  They both eventually end up being the function-call style
post-analysis.
I don't think the pretty printer for the new form is ideal yet; it will
work but might not actually produce particularly pretty output.

Syntactic sugar for CASE

---

soql-standalone-parser/src/main/jflex/SoQLLexer.flex

They currently _do not_ nest (which is the same behavior as C
```
> select /* haha */ 1 /* gnu */
Outputs:
_1 .. 1 :: number
None
None
has aggregates: false
```

Add /* .. */-style block comments.

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/mapping/ColumnIdMapper.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
version.sbt

Make from context available to lateral join (previously only contexts from preceding joins are available)

EN-44901: Make from (via this alias) context available to lateral join

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/exceptions/Exceptions.scala
soql-environment/src/main/scala/com/socrata/soql/environment/DatasetContext.scala
soql-environment/src/main/scala/com/socrata/soql/environment/TableName.scala

This is so that you can create virtual tables containing a single row
(e.g., to force single evaluation of expressions) in a manner like this
```
select x, y, z
join (select something_expensive() as a from @single_row) as vars on true
where x > @vars.a
```
and ultimately get generated SQL that looks something like
```
select x, y, z
join (select something_expensive() as a) vars -- note no FROM clause here
where x > vars.a
```
This is a bit of a workaround for the fact that a SoQL expression
with no `FROM` clause means "select from the current ambient table",
contrary to SQL.

Add a `single_row` predefined alias

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/exceptions/Exceptions.scala
soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/typed/Join.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerQueryOperatorTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-environment/src/main/scala/com/socrata/soql/environment/HoleName.scala
soql-standalone-parser/src/main/jflex/SoQLLexer.flex
soql-standalone-parser/src/main/scala/com/socrata/soql/BinaryTree.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Join.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/RewriteFailure.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/standalone_exceptions/BadParse.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/RewriteTest.scala
soql-toy/src/main/scala/com/socrata/soql/SoqlToy.scala
soql-toy/src/test/scala/com/socrata/soql/SoQLTypeAnalyzerTest.scala

* Introduce a "hole" AST node which represents a parameter
* Allow JoinSelect to express join-to-function
* Keep From-qualifiers around when analyzing (fixes a bug in SQL generation)

Support for UDFs

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerQueryOperatorTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-environment/src/main/scala/com/socrata/soql/environment/TableName.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/mapping/ColumnNameMapperTest.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/parsing/ToStringTest.scala

Before: table aliases were declared with `AS identifier` where
"identifier" had to conform to the lexical rules for identifier-ness.
Now: table aliases can still be declared that way, but they can
also be declared with `AS @tablename`.  This has two advantages:
1. It makes declaration reflect use.
2. Lexically it allows 4x4s to be used for table identifiers.
Note that even before, `@tablename` wasn't necessarily always a 4x4,
thanks to resource names.
The upshot of all this is that we can expand `JOIN @some-thng` where
"some-thng" is a derived view or other structure that isn't just a
bare table into `JOIN (select ...) AS @some-thng` and have it work.
Also this makes the alias on table-functions optional, as we can use
the function-name as the alias reliably now.

Table alias rework

---

soql-analyzer/src/main/scala/com/socrata/soql/AnalysisDeserializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/AnalysisSerializer.scala
soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/mapping/ColumnIdMapper.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/BinaryTree.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/AbstractParser.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/BinaryTreeSelectTest.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/mapping/ColumnNameMapperTest.scala
version.sbt

Previously, parentheses can only influence the left, right structure of binary tree.  This doesn't work well with set operations that are different in precedence, for example:
(SELECT a FROM a UNION SELECT b FROM b) INTERSECT SELECT c FROM c

Be able to preserve parentheses in compound queries

---

soql-analyzer/src/main/scala/com/socrata/soql/exceptions/Exceptions.scala
soql-analyzer/src/main/scala/com/socrata/soql/parsing/Parser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/StandaloneParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/standalone_exceptions/BadParse.scala

In particular, tell the user that `:*` and `*` must come first, and
that `:*` must come before `*`.

Produce better error messages around *-positioning in select lists.

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
version.sbt

Adding:
`area` => ST_Area - return the area of a geometry
`polygon_intersection` => ST_Intersection - return the geometry of a an intersecting area (or null if they don't intersect)
`ntile(N)` => NTILE - integer ranging from 1 to the argument value, dividing the partition as equally as possible. Useful for getting quantiles through SoQL.
Bump version

add wrapper for ST_Area, ST_Intersection, and NTILE(N) functionality

---

project/SoqlParser.scala

Corrects a stack overflow error when pretty-printing function calls
with extremely long parameter lists

Bump prettyprinter

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

It was not of general use and for a feature that was never completed,
so we're just getting rid of it entirely.

Remove snap_for_zoom

---

soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/mapping/ColumnNameMapperTest.scala
version.sbt

Pass generateAliases down to right compound query in ColumnNameMapper

Support union queries in rollup

---

soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/mapping/ColumnNameMapperTest.scala
version.sbt

regression from adding join/multi-table support in rollup - EN-51708

EN-52940: Rollup query select column alias cannot be used in group by

---

soql-analyzer/src/main/scala/com/socrata/soql/typechecker/Typechecker.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
version.sbt

bug: 'select `name_first` as name_last, @a1.`name_last` as a1_name_last' was resolving a1_name_last as a column ref of `name_first` on the not-joined dataset
this was because we did not take the selection qualifier into account when looking up the column in the alias map.

EN-54117: stop resolving joined (qualified) cols to aliased selections

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
version.sbt

* make it more explicit about accepting both starting point and optionally ending point, provide examples
* frontend is still going to show just one argument in the function signature, but reading +using the variable arguments is probably a frontend change

EN-55321: update substring function docs

---

soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
version.sbt

For a new param, we would generate a name like
param_aaaa-aaaa_something, and that would fail column name validation in core since it doesn't allow dashes

EN-54831 do not automatically insert a dash in generataed aliases

---

soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala

Otherwise render `count_distinct(...)`

Only render `count(distinct ...)` sugar if there is exactly 1 arg

---

soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala

It goes away in Java 11.  Since our minimum supported version is java
8, use the new-in-Java-8 `java.util.Base64` class instead.

Remove usage of javax.xml.bind for base64 stuff

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Expression.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Merge.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/PositionInfo.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/AggregateFunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/Column.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/FunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/LiteralValue.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/NullLiteral.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/SelectListReference.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/WindowedFunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestTypeInfo.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala

We now have the notion of "logical position" and "physical position". The physical is where an Expr comes from physically within a query's text. If that expr is copied to another position in the text (e.g., via alias expansion or UDF parameter substitution) the logical position is updated to refer to the place the expression has been expanded into.

Track expression positions with more nuance

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

If we want it, we can put it back in as a postprocessing pass easily enough, but PG seems to understand this idiom (so that's probably not necessary) and keeping it introduces an edge case in the "use an analysis to decorate a parse tree with types" code whereby a simple parameter which isn't actually used in the UDF's expansion would just not get annotated.

Remove UDF simple parameter optimization

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

Provide prototypes for LEAD and LAG which include their optional "offset" and "default" parameters, and provide a function for turning a fixed_timestamp into an epoch-seconds number.

EN-57267, EN-57268: Optional params for LAG and LEAD, epoch_seconds

---

soql-types/src/main/scala/com/socrata/soql/types/SoQLGeometryLike.scala

Fallout of 9e6696805c76b5511cd0e1198bb19a0700222b8e - the old base64 decoder was more lenient, and java.util's is stricter.  So where the old CJSON WKT decode codepath was "decode base64, then fail to parse WKB, then try as WKT", the new one would throw an exception at that first step.
So.. don't do that.  If it's not valid base64, just return None straightaway and don't even try to parse Wkb.

Fix WKT JSON decoding

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/From.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Statement.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromSingleRow.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromStatement.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromTable.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/Join.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Merger.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/PreserveOrdering.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveUnusedColumns.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/SelectListReferences.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/CTE.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/CombinedTables.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Values.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

Mostly pulling it them out into their own files, and putting them all in the `rewrite` sub-package of analyzer2, but also heavily reworking the preserveOrdering rewrite so that it doesn't need the `row_number` function anymore (which both makes it easier to use and might let PG's query optimizer see what we're doing with this?)

Refactor various rewrite-pass stuff

---

soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Select.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentParser.scala

In order to make this not a completely horrible mess of duplicated logic, this entailed a refactor of the parser to encode precedence more explicitly (which has the pleasing side-effect of removing a bunch of code there, at the cost of using slightly more stack-space at runtime)

Teach the soql-renderer about precedence

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/MockTableFinder.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/TableFinder.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/package.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TableFinderTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestHelper.scala

Plus aliases for the various error types for ease of use, and a no-longer-relevant todo comment removed.

TableFinder.Result is just Either

---

soql-standalone-parser/src/main/jflex/SoQLLexer.flex
soql-standalone-parser/src/main/scala/com/socrata/soql/ast/Expression.scala

Because JSON-style strings with control characters print in a more useful way than SQL-style.

When pretty-printing strings, use JSON-style rather than SQL-style

---

project/SoQLSerialize.scala

The whole point of this subproject is to serialize things using this library

protobuf shouldn't be an optional dep of soql-serialize

---

soql-standalone-parser/src/main/scala/com/socrata/soql/mapping/ColumnNameMapper.scala
soql-standalone-parser/src/test/scala/com/socrata/soql/mapping/ColumnNameMapperTest.scala
version.sbt

We now support creating rollups for piped queries.
Parts of the column name mapping logic was changed for this.
There is a section of code during selection mapping that is preventing aliases from being generated, causing queries to fail to rewrite to rollups.

EN-55220: Fix to column name mapper, do generate aliases

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/From.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromSingleRow.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromStatement.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromTable.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/Join.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveTrivialSelects.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

Before it would consider removing a trivial select only if it were the _only_ input dataset to a query.  Now it will do for all trivial-select inputs even in the presence of joins.

Generalize "remove trivial selects"

---

build.sbt
project/SoqlDocs.scala
soql-analyzer/src/main/scala/com/socrata/soql/functions/Function.scala
soql-analyzer/src/main/scala/com/socrata/soql/functions/MonomorphicFunction.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestFunctions.scala
soql-analyzer/src/test/scala/com/socrata/soql/types/TestFunctions.scala
soql-docs/src/main/scala/com/socrata/soql/docs/Docs.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

* It's now a single aggregate object instead of a pair of fields
* This aggregate object also has a normal/deprecated/hidden status field
* Fix the SoQLDocs subproject (and make sure it's actually built in a normal build to prevent bitrot)
This will probably be a mildly disruptive change, though _most_ things neither build nor destructure Functions so it shouldn't be too bad.

EN-60580: Change how function docs are represented

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

Changing it from:
substring(text, number, number*)
to:
substring(text, number)
substring(text, number, number)

Fix `substring` prototype

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveUnusedColumns.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Values.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

Specifically it just always assumed that a values statement never used any columns itself, which is not necessarily true if lateral joins are involved.

"Remove used columns" was too aggressive on values statements

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLTypeInfo.scala
soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala
version.sbt

Rather than quasi-magical casts that the sqlizer knows about

Recognize phone, url, and textified boolean literals as LiteralValues

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Expression.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/From.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Isomorphism.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Statement.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/AggregateFunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/PhysicalColumn.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/from/FromTable.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

Before:
* You could only check entire Statements for equivalence, because the check needed to build up a map of table labels to database table names.
Now:
* You can check Statements, Froms, and Exprs for equivalence.

Make expression isomorphism easier

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/Select.scala

By making an overconstrained ORDER BY on a candidate be accepted when doing that match

Make "vertical slice" match more candidates

---

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/ExprSqlizer.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/GensymProvider.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/SqlNamespaces.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Sqlizer.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/SqlizerUniverse.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/package.scala

* Separate more cleanly query-specific parts of the parameters and the non-query-specific parts
* and also make SqlNamespace stateless (gensyms are now separate)
* Which means we can create a sqlizer once at startup and reuse it over and over
* Unfortunately the Rep provide is still pretty query-specific, but it's the only piece.

Refactor the sqlizer

---

soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
version.sbt

This adds PostgreSQL's `unaccent` function for removing diacritics from a string:
```
unaccent('Sainte-Thérèse, Québec') => 'Sainte-Therese, Quebec'
```
Per [discussion with Robert M.](https://di-tylertech.slack.com/archives/C0EFEMN7N/p1697050043137879?thread_ts=1696961907.732169&cid=C0EFEMN7N), this will also require adding a migration in [socrata-platform/soql-postgres-adapter](https://github.com/socrata-platform/soql-postgres-adapter) for the unaccent extension — PR to follow.

Add unaccent SOQL function

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/AdHocRewriter.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupExact.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestFunctions.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestType.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupExactTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/rollup/RollupTestHelper.scala
soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLAdHocRewriter.scala
soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLRollupExact.scala
soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLAdHocRewriterTest.scala

And implement it for comparing a possibly-truncated timestamp to a pre-truncated literal.  This implements it for comparison operators but _not_ for BETWEEN (even though the old-rollup matcher _does_ do BETWEEN) because `x BETWEEN y AND z` is `y <= x AND x <= z`, and that upper bound can't correctly be rewritten in this way)

Add a concept of ad-hoc rollup rewrite rules

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLError.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala

Also add a thing to make the 2.12 compiler stop whining that I'm using higher-kinded types without warning it first.

Add make_point

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLError.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/package.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLErrorTest.scala
soql-utils/src/main/scala/com/socrata/soql/util/EncodedError.scala
soql-utils/src/main/scala/com/socrata/soql/util/ErrorHierarchyCodecBuilder.scala
soql-utils/src/main/scala/com/socrata/soql/util/ErrorHierarchyDecodeBuilder.scala
soql-utils/src/main/scala/com/socrata/soql/util/ErrorHierarchyEncodeBuilder.scala
soql-utils/src/main/scala/com/socrata/soql/util/package.scala

* Make `"position"` an optional top-level property of the encoded error
* `"code"` ⇒ `"type"` as the for the error type tag
Plus some QOL improvements:
* `errorCodecs` by convention now defaults to an empty builder parameter
* `SoQLErrorCodec#result` is no longer overloaded (though its arguments are)
And a correction:
* No longer expose ErrorHierarchyCodec stuff

Make the error change less churn-inducing

---

soql-utils/src/main/scala/com/socrata/soql/util/EncodedError.scala
soql-utils/src/main/scala/com/socrata/soql/util/ErrorHierarchyCodecBuilder.scala
soql-utils/src/main/scala/com/socrata/soql/util/ErrorHierarchyEncodeBuilder.scala

Before, the only way to do this conversion once you have collection of errors would be to serialize to JSON and then deserialize to an EncodedError.  This lets you skip the middle step and go directly to an EncodedError.

Add error-to-encodederror conversion

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/ImposeOrdering.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/PreserveUnique.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/statement/CombinedTables.scala

Specifically, teach CombinedTables#unique about the meanings of table funcs, and un-teach ImposeOrdering about them.  This greatly simplifies ImposeOrderings.

Rework CombinedTables' notion of unique columns

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/AddLimitOffset.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/LimitIfUnlimited.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/NonNegativeBigInt.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Pass.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/TestHelper.scala

Specifically, don't allow someone to create a rewrite pass with an invalid limit or offset in the first place, rather than crashing with a "requirement failed" message when given such an invalid value.  This'll let us return a "bad request" when deserializing a Pass fails rather than crashing later.

Catch invalid limits and offsets in rewrite passes earlier

---

soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/UserParameters.scala
soql-types/src/main/scala/com/socrata/soql/types/cjson.scala

Reduces code duplication, especially for the timestamp types.
And, importantly, makes it so that a "number" parameter will accept either an actual JSON number or a string-containing-a-number in the value field, which increases consistency with ingress.

Use the CJSON reps for UserParameters

---

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Rep.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/SqlNamespaces.scala
soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestHelper.scala
soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestRepProvider.scala

Before:
* `SqlNamespaces` had an abstract method `rawDatabaseColumnBase`, which was assumed to be a thing onto which further identifierish stuff could be appended.
Now:
* `SqlNamespaces` has two methods, both named `rawDatabaseColumnName`. The one with a "suffix" parameter should create a name which should be in some sense "like" `rawDatabaseColumnName(dcn) + "_" + suffix`.

Allow sqlizer implementations more control over column namespacing

---

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Rep.scala
soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestRepProvider.scala
soql-types/src/main/scala/com/socrata/soql/types/obfuscation/CryptProvider.scala

For use in places where values get (sometimes implicitly) converted to text.

EN-66000: Infrastructure for generalized convert-to-text

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/NamedExpr.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rollup/RollupExact.scala
soql-stdlib/src/main/scala/com/socrata/soql/functions/SoQLFunctions.scala
soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLAdHocRewriter.scala
soql-stdlib/src/main/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLFunctionSubset.scala
soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLAdHocRewriterTest.scala
soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLFunctionSplitterTest.scala
soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLFunctionSubsetTest.scala
soql-stdlib/src/test/scala/com/socrata/soql/stdlib/analyzer2/rollup/SoQLRollupTestHelper.scala
soql-types/src/main/scala/com/socrata/soql/types/SoQLType.scala

* Field-syntax access for parts of floating_timestamps, dates, and times
** including fieldlike access to "date" and "time" parts of timestamps
* Add a time to a date to get a floating_timestamp
* Add or subtract an interval to a time to get a new time
* Subtract two times to get an interval
* Add an interval to a date to get a floating_timestamp (not sure why
the discrepancy, but it's what PG does)
* Subtract an interval from a date to get a floating_timestamp
* Find the difference between two dates in days
* Truncate a date at year or month
* Convert timestamps, dates, times, intervals to ISO8601 via cast-to-text
* Convert row identifiers and row versions to text via cast

More functions!

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveUnusedOrderBy.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

"Trivial" here means "selects some untransformed columns from a physical table, with no other processing".  The main use case is where it deletes a default ordering from a joined-to dataset, so it doesn't need to be a subselect anymore.

Remove trivial subselect introduced by RemoveUnusedOrderBy

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

Which means "at least one parameter to the UDF contains a column ref"

Only mark a join-to-a-UDF implicitly LATERAL if it needs to be

---

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Rep.scala
soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/ResultExtractor.scala
soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/TestRepProvider.scala

When using a cursor, pg does not want to use parallel query plans.  So, in order to preserve streaming, instead we'll COPY out results.  This means teaching the reps to be able to parse results out of CSVs as well as from result sets.
I don't entirely like this; it's putting too much pg specific code in here (for that matter, even taking a ResultSet before was pretty overly-specific for what the Sqlizer wants to be).  I think I want to refactor this so that either:
* Sqlizer is a class with an abstract ResultExtractor type which can be implemented per-secondary
* Sqlizer doesn't return a ResultExtractor at all, just schema information.
..but that can wait until later.

Improve query plans in postgresql by using COPY

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalysis.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Pass.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveSyntheticColumns.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

This is nicer than doing it as a postprocessing pass in core because it allows the removal to be propagated through the whole query via the "remove unused columns" pass.

Add a "remove synthetic columns" rewrite pass

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Pass.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveOutputColumns.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveSyntheticColumns.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/RemoveSystemColumns.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala
soql-environment/src/main/scala/com/socrata/soql/environment/ColumnName.scala

Much like "remove synthetic columns", this exists as a rewrite pass so that a subsequent "remove unused columns" pass can do a deeper rewrite.
This factors out the common functionality between those two operations into a common "remove output columns according to a predicate" helper.

Add a "remove system columns" rewrite pass

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLError.scala

* Where they include a user-provided name, delineate that name with quotes.  E.g., instead of `No such column a` generate ``No such column `a'``
* For a type mismatch error, say what was expected, not just what was found.

Improve error messages a little

---

soql-json-utils/src/main/scala/com/socrata/soql/jsonutils/package.scala

I still want to stop using Position altogether eventually (because it's weird that the JSON serialization of a SoQLPosition loses information) but this is just an off-by-one error and can be fixed.

EN-67656: Fix off-by-one error in Position deserializer

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala

Squash is used to say "here are a bunch of exprs of possibly different types; for each type, select the most preferable one.  It was producing a Stream unnecessarily which was building up into an enormous force event that overflowed the stack on long argument lists.

EN-69963: Be less lazy in `squash`

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/ImposeOrdering.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

* Single row aggregates require no ordering to be added
* For grouped aggregates, try ordering by the grouping expressions first, before falling back to whatever `select.unique` says.

Better impose-ordering

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/AggregateFunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/FunctionCall.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/expression/WindowedFunctionCall.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

This lets you use select list references in them, as long as the select- list column you're referencing only itself references tables that have been established at the point the ON column exists.
There's still an unfortunate thing here because it would also be nice to do this same sort of thing for LATERAL joins, but that would be a much more major restructuring, since the output of the FROM-clause's typechecking is used as the input to typechecking the select-list, so it becomes circular.  This ON clause change was easy because they don't affect the query's input schema at all, just which rows exist.

Delay typechecking of ON clauses

---

soql-analyzer/src/main/scala/com/socrata/soql/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/aliases/AliasAnalysis.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLError.scala
soql-analyzer/src/test/scala/com/socrata/soql/SoQLAnalyzerTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/aliases/AliasAnalysisTest.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

In the OA, you weren't allowed to reference semi-explicitly aliased foreign columns in other parts of the query, more or less accidentally. The NA allowed it.  This change makes the NA behavior closer to the OA behavior here.

Old-analyzer/new-analyzer compatibility around joined column aliases

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Environment.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Levenshtein.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLError.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Typechecker.scala
soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/Util.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

When we can't find a column, go through the names that are available and if it's "close enough" as measured by Levenshtein distance plus a heuristic around qualifier-absence, report it as a possibility.

Better "no such column" error.

---

soql-standalone-parser/src/main/jflex/SoQLLexer.flex
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/LexerReader.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/parsing/RecursiveDescentParser.scala
soql-standalone-parser/src/main/scala/com/socrata/soql/tokens/Tokens.scala

The parser strips them out, but this means we don't forget about them _entirely_ early on.

Include comments in the lexer stream

---

soql-sqlizer/src/main/scala/com/socrata/soql/sqlizer/Sqlizer.scala
soql-sqlizer/src/test/scala/com/socrata/soql/sqlizer/SqlizerTest.scala

If we would generate `SELECT [nothing]` then instead generate `SELECT 1` because redshift doesn't like empty select-lists.

Don't sqlize empty select lists

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/SoQLAnalyzer.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalyzerTest.scala

When we remove hidden columns from tables, we need to also consider any PK column group which contains such a column as no longer being a valid PK.  Otherwise later on we can crash when we assume that the pk list always contains lists of real column

EN-81036: Remove PK-sets that contain hidden columns

---

soql-analyzer/src/main/scala/com/socrata/soql/analyzer2/rewrite/Merger.scala
soql-analyzer/src/test/scala/com/socrata/soql/analyzer2/SoQLAnalysisTest.scala

Instead of trusting an empty group by to imply it, because that's just wrong.

EN-82509: Make the merger even more explicit about aggregatedness
